version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    networks:
      - nextjs-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
